language:
  python
python:
  - 2
  - 2.6
  - 2.7
  - 3
  - 3.2
  - 3.3
  - 3.4
  - 3.5

install:
  - pip install --upgrade pip
  - pip install -r requirements.txt
  - pip install flake8
  - pip install coveralls

script:
  - flake8 wifiPassword

after_success:
  coveralls